server:
  port: 8080
  servlet:
    context-path: /mj
logging:
  level:
    ROOT: info
    com.github.novicezk.midjourney: debug
knife4j:
  enable: true
  openapi:
    title: starxmate.com mj api 
    description: starxmate.com mj api
    concat: starxmate.com
    url: starxmate.com
    version: v2.5.4
    terms-of-service-url: starxmate.com
    group:
      api:
        group-name: API
        api-rule: package
        api-rule-resources:
          - com.github.novicezk.midjourney.controller